# Docker Compose for Kosera API Production
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: kosera-db-prod
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kosera}
      POSTGRES_USER: ${POSTGRES_USER:-kosera}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kosera-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-kosera} -d ${POSTGRES_DB:-kosera}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Next.js Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: kosera-app-prod
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kosera-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: kosera-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - kosera-network

volumes:
  postgres_data:
    driver: local

networks:
  kosera-network:
    driver: bridge
