version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kosera-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kosera
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kosera"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - kosera-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kosera-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kosera.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kosera-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local

networks:
  kosera-network:
    driver: bridge
