name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint / Type / Unit / Integration
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: kosera_test
          POSTGRES_USER: kosera
          POSTGRES_PASSWORD: kosera123
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U kosera -d kosera_test" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=10
    env:
      DATABASE_URL: postgresql://kosera:kosera123@localhost:5433/kosera_test
      NEXT_TELEMETRY_DISABLED: '1'
      NODE_ENV: test
      JWT_SECRET: ci-test-secret
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Sync DB Schema (Drizzle push)
        run: npm run db:push:test

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Unit Tests
        run: npm run test:unit

      - name: Integration Tests
        run: npm run test:integration

      - name: Coverage (optional)
        run: npm run test:coverage || true

  build:
    name: Build Next App
    runs-on: ubuntu-latest
    needs: test
    env:
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          retention-days: 7