name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint, Type Check, Test, Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: kosera
          # Gunakan secret untuk password
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: kosera
        # Health check ini sudah cukup untuk memastikan DB siap
        options: >-
          --health-cmd "pg_isready -U kosera"
          --health-interval 5s
          --health-timeout 5s
          --health-retries: 12

    env:
      NEXT_TELEMETRY_DISABLED: '1'
      CI: 'true'
      # Gunakan secret untuk password dan kunci lainnya
      DATABASE_URL: postgresql://kosera:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/kosera
      JWT_SECRET: ${{ secrets.JWT_SECRET_CI }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # HAPUS STEP "Wait for Postgres" DARI SINI

      - name: Apply migrations
        run: npx drizzle-kit push

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          retention-days: 7